#!/bin/bash
# Script de inicio rápido para To-Do List App
# Uso: Copiar este contenido en un archivo .sh o ejecutar líneas manualmente

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        TO-DO LIST APP - GUÍA DE INICIO RÁPIDO               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📁 Paso 1: Navegar a la carpeta del proyecto"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ejecuta:"
echo "  cd \"c:\\Users\\Maske\\Desktop\\proyecto final\\todo-list-app\""
echo ""

echo "📦 Paso 2: Instalar dependencias"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ejecuta:"
echo "  npm install"
echo ""
echo "⏳ Esto puede tomar 1-2 minutos en la primera instalación"
echo ""

echo "🚀 Paso 3: Ejecutar la aplicación"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ejecuta:"
echo "  npm run dev"
echo ""
echo "✅ La app se abrirá automáticamente en http://localhost:3000"
echo ""

echo "📝 Opciones adicionales:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "▶ Para compilar para producción:"
echo "  npm run build"
echo ""
echo "▶ Para ver el build de producción:"
echo "  npm run preview"
echo ""
echo "▶ Para detener el servidor:"
echo "  Ctrl+C en la terminal"
echo ""

echo "📚 Documentación disponible:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📄 README.md          - Documentación principal"
echo "  📄 INSTRUCCIONES.md   - Guía de instalación"
echo "  📄 ESTRUCTURA.md      - Explicación técnica"
echo "  📄 TROUBLESHOOTING.md - Solución de problemas"
echo "  📄 VISUAL.md          - Diagramas y diseño"
echo "  📄 ARCHIVOS.md        - Lista de archivos"
echo ""

echo "🎯 Si tienes problemas:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Lee INSTRUCCIONES.md"
echo "  2. Consulta TROUBLESHOOTING.md"
echo "  3. Revisa la consola del navegador (F12)"
echo ""

echo "✨ ¡Listo para usar! ✨"
echo ""
echo "Próximos pasos:"
echo "  1. Instala dependencias (npm install)"
echo "  2. Ejecuta la app (npm run dev)"
echo "  3. ¡Comienza a crear tareas!"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
